apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exchange
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exchange
        tier: frontend
    spec:
      containers:
      - name: exchange
        image: nginx  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
