apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: screenshot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: screenshot
        tier: backend
    spec:
      containers:
      - name: screenshot
        image: gcr.io/gcastle-gke-dev/screenshot:v1  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
